### ISSUE TITLE
BatchBuilder: For Media Preservation, v2.3.0 can't connect to Wordshack via BB CLI

### ISSUE THREAD

**Issue by juliewetherill** [harvard-lts/epadd#48]
This issue was reported by Kaylie Ackerman on 7/15 as part of big file batch testing in QA DRS. LTS (Paul and Julie) have not been able to reproduce this issue. But there are a lot of unknowns about the MPS batch setup, which is scripted and very customized.

Problem: In the MPS 2.3.0 BB setup, using CLI, the call to Wordshack API (first thing it does when initialized) is timing out which causes the CLI process to stop. Below is the error stack Kaylie reported:
///
I added the storage class properties at the file level and I am still being stopped by this wordshack connection issue. I don’t have this issue with the BB I use everyday.

dhcp-140-247-199-208:BatchBuilder-2.3.0-SNAPSHOT dackerm$ ./batchbuildercli.sh -advanced video -d /Volumes/mediapres2/_drs-dropbox/WAITINGFORDRS/20210607-140646-001/RA_VT-037.1/
120280 [main] ERROR edu.harvard.hul.ois.wordshack.client.WordshackClient  - Caught exception in callURLGet()
org.apache.http.conn.ConnectTimeoutException: Connect to wordshack-dev.lib.harvard.edu:10038 timed out
        at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:129)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
        at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
        at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:640)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:784)
        at edu.harvard.hul.ois.wordshack.client.WordshackClient.callURLGet(WordshackClient.java:644)
        at edu.harvard.hul.ois.wordshack.client.WordshackClient.getTermLabelsIDMap(WordshackClient.java:306)
        at edu.harvard.hul.ois.bb.model.BBApp.init(BBApp.java:317)
        at edu.harvard.hul.ois.bb.model.BBApp.<init>(BBApp.java:183)
        at edu.harvard.hul.ois.bb.cli.BBCliApp.<init>(BBCliApp.java:108)
        at edu.harvard.hul.ois.bb.cli.BBAdvancedCliApp.<init>(BBAdvancedCliApp.java:111)
        at edu.harvard.hul.ois.bb.cli.AdvancedVideoCli.<init>(AdvancedVideoCli.java:62)
        at edu.harvard.hul.ois.bb.cli.BBCli.run(BBCli.java:309)
        at edu.harvard.hul.ois.bb.cli.BBCli.main(BBCli.java:68)
Unable to load log4j.properties file: intentional/fake/path -- reason: Not a valid file
Falling back to default log4j.properties file: .//fits/log4j.properties
120335 [main] INFO edu.harvard.hul.ois.fits.Fits  - Logging initialized with: file:/usr/local/HCL-APS_2.0/common/BatchBuilder-2.3.0-SNAPSHOT/./fits/log4j.properties
///

**Comment by juliewetherill** [comment]
I think Kaylie’s problem is caused by bad parameter values in the bb.properties file that ships with BB2.3.0SNAPSHOT. (H/T Vitaly)

I just sent Kaylie the correct properties file with instructions for installing it. Asked her to try QA batch deposit again.

The problem we need to fix: 
In the 2.3.0 zip archive, the default bb.properties file is not pointing at prod DRS like it should -- parameters in the file are for dev DRS. Contributing factor-- Kaylie isn't very familiar with using BB properties file so isn't aware of changing the active DRS instance by changing properties files.

The .dev, .qa, and .prod copies of the properties files that ship with 2.3.0 are fine. It's just the default version that is wrong.

**Comment by ives1227** [comment]
I will make these changes to the properties file.

**Comment by ives1227** [comment]
This bug was fixed by @juliewetherill so I created a new story to cover what needs to happen to prevent it from happening again. #53
